#!/usr/bin/env node
/**
 * Generates the résumé from content/portfolio.json, following Anuj's
 * existing CV structure:
 *
 *   header (name · title · location · email · phone)
 *   sidebar block: Status / Skills / Interests / Activities
 *   Summary · Synopsis · Experience · Accomplishments
 *   Activities and Hobbies · Languages · Education
 *
 * Output: public/resume.html — print-ready A4, and directly linkable.
 * Print to PDF from the browser (Ctrl+P → Save as PDF, margins "Default",
 * background graphics on) to produce public/resume.pdf.
 *
 *   npm run resume:build
 */
import fs from 'node:fs';
import path from 'node:path';
import { loadContent, ROOT } from './lib/content.mjs';

const c = loadContent();
const out = path.join(ROOT, 'public', 'resume.html');

const esc = (s) =>
  String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

const bullets = (items) =>
  (items || []).map((b) => `<li>${esc(b)}</li>`).join('\n          ');

const dl = (label, value) => `
        <div class="row">
          <div class="k">${esc(label)}</div>
          <div class="v">${esc(value)}</div>
        </div>`;

const section = (title, body) => `
      <section>
        <h2>${esc(title)}</h2>
        ${body}
      </section>`;

const experience = (c.experience || [])
  .map(
    (e) => `
        <div class="entry">
          <div class="when">${esc(e.period)}</div>
          <div class="what">
            <div class="head">
              <span class="role">${esc(e.role)}</span>
              <span class="org">${esc(e.org)}${e.location ? `, ${esc(e.location)}` : ''}</span>
            </div>
            <ul>
          ${bullets(e.highlights)}
            </ul>
          </div>
        </div>`,
  )
  .join('');

const education = (c.education || [])
  .map(
    (e) => `
        <div class="entry">
          <div class="when">${esc(e.period)}</div>
          <div class="what">
            <div class="head">
              <span class="role">${esc(e.degree)}</span>
              <span class="org">${esc(e.school)}</span>
            </div>
            ${e.detail ? `<p class="detail">${esc(e.detail)}</p>` : ''}
          </div>
        </div>`,
  )
  .join('');

const contact = [
  c.profile.resumeTitle,
  c.profile.location,
  c.profile.email,
  c.profile.phone,
]
  .filter(Boolean)
  .map(esc)
  .join(' <span class="sep">·</span> ');

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(c.profile.name)} — Résumé</title>
<style>
  /* Generated by scripts/build-resume.mjs — edit content/portfolio.json, not this file. */
  @page { size: A4; margin: 14mm 14mm 12mm; }

  :root {
    --ink: #14201e;
    --ink-2: #414d4b;
    --ink-3: #6e7a77;
    --rule: #c6cac6;
    --ch: #0a6e68;
    --paper: #ffffff;
    --display: "Iowan Old Style", "Palatino Linotype", "Book Antiqua", Palatino, Georgia, serif;
    --body: "Segoe UI Variable Text", "Segoe UI", -apple-system, BlinkMacSystemFont, Arial, sans-serif;
    --data: "Cascadia Mono", Consolas, ui-monospace, "SF Mono", monospace;
  }

  * { box-sizing: border-box; }

  body {
    margin: 0;
    background: #e8eae7;
    color: var(--ink);
    font-family: var(--body);
    font-size: 10.2pt;
    line-height: 1.42;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
  }

  .sheet {
    background: var(--paper);
    max-width: 210mm;
    margin: 18px auto;
    padding: 16mm 15mm;
    box-shadow: 0 2px 18px #14201e1f;
  }

  header.mast { border-bottom: 1.5px solid var(--ink); padding-bottom: 9px; margin-bottom: 16px; }
  h1 {
    font-family: var(--display);
    font-size: 23pt;
    line-height: 1;
    letter-spacing: -0.02em;
    margin: 0 0 6px;
    font-weight: 600;
  }
  .contact { font-family: var(--data); font-size: 8.4pt; color: var(--ink-2); letter-spacing: 0.01em; }
  .contact .sep { color: var(--ch); padding: 0 3px; }

  h2 {
    font-family: var(--data);
    font-size: 8pt;
    /* ATS-critical: above roughly 0.1em of tracking, PDF text extraction
       inserts a space between every letter, so "EXPERIENCE" is read as
       "E X P E R I E N C E" and a parser looking for the section heading
       finds nothing. Verified by extracting the rendered PDF. Keep this in
       step with .row .k, which extracts cleanly at the same value. */
    letter-spacing: 0.09em;
    text-transform: uppercase;
    color: var(--ch);
    margin: 0 0 7px;
    padding-bottom: 3px;
    border-bottom: 1px solid var(--rule);
  }
  section { margin-bottom: 15px; }
  section:last-child { margin-bottom: 0; }

  /* Status / Skills / Interests / Activities */
  .row { display: grid; grid-template-columns: 74px 1fr; gap: 10px; margin-bottom: 4px; }
  .row .k {
    font-family: var(--data);
    font-size: 7.6pt;
    text-transform: uppercase;
    letter-spacing: 0.09em;
    color: var(--ink-3);
    padding-top: 1.5px;
  }
  .row .v { color: var(--ink-2); }

  p { margin: 0 0 7px; }
  p:last-child { margin-bottom: 0; }

  ul { margin: 4px 0 0; padding-left: 15px; }
  li { margin-bottom: 2.5px; color: var(--ink-2); }
  li::marker { color: var(--ch); }

  /* dated entries — the left date column from the original template */
  /* 112px, not 74px: a full range like "09/2024 - 01/2026" is 17 monospace
     characters and wrapped onto two lines in the narrower column, splitting the
     date an ATS is trying to read. Verified against the extracted PDF text. */
  .entry { display: grid; grid-template-columns: 112px 1fr; gap: 10px; margin-bottom: 11px; }
  .entry:last-child { margin-bottom: 0; }
  .entry .when {
    font-family: var(--data);
    font-size: 7.8pt;
    color: var(--ch);
    padding-top: 2px;
    font-variant-numeric: tabular-nums;
  }
  .entry .head { display: flex; justify-content: space-between; gap: 10px; align-items: baseline; }
  .entry .role { font-family: var(--display); font-size: 11.6pt; font-weight: 600; }
  .entry .org { font-family: var(--data); font-size: 8.2pt; color: var(--ink-3); text-align: right; }
  .entry .detail { font-family: var(--data); font-size: 8.4pt; color: var(--ink-2); margin: 2px 0 0; }

  .two-col { column-count: 2; column-gap: 22px; }
  .two-col li { break-inside: avoid; }

  @media print {
    body { background: #fff; }
    .sheet { margin: 0; padding: 0; box-shadow: none; max-width: none; }
    /* Deliberately no break-inside rule on section: Experience is one section,
       so forbidding a break inside it pushes the whole block to a fresh page
       the moment it outgrows the space left on page 1 — leaving a half-empty
       page and spilling onto a third. Keep a single job entry together
       instead, which is the granularity that actually matters. */
    .entry { break-inside: avoid; }
    h2 { break-after: avoid; }
  }
</style>
</head>
<body>
  <div class="sheet">
    <header class="mast">
      <h1>${esc(c.profile.name)}</h1>
      <div class="contact">${contact}</div>
    </header>
${section(
  'Profile',
  `${dl('Status', c.sidebar.status)}
${dl('Skills', (c.sidebar.skills || []).join(', '))}
${dl('Interests', (c.sidebar.interests || []).join(', '))}
${dl('Activities', (c.sidebar.activities || []).join(', '))}`,
)}
${section('Summary', `<p>${esc(c.summary.resume)}</p>`)}
${section('Synopsis', `<ul>\n          ${bullets(c.synopsis)}\n        </ul>`)}
${section('Experience', experience)}
${section('Accomplishments', `<ul>\n          ${bullets(c.accomplishments)}\n        </ul>`)}
${section('Activities and Hobbies', `<ul>\n          ${bullets(c.hobbies)}\n        </ul>`)}
${section(
  'Languages',
  (c.languages || []).map((l) => dl(l.name, l.level)).join(''),
)}
${section('Education', education)}
  </div>
</body>
</html>
`;

fs.writeFileSync(out, html, 'utf8');

const counts = {
  synopsis: c.synopsis?.length ?? 0,
  experience: c.experience?.length ?? 0,
  'experience bullets': (c.experience || []).reduce((n, e) => n + (e.highlights?.length ?? 0), 0),
  accomplishments: c.accomplishments?.length ?? 0,
  education: c.education?.length ?? 0,
};

console.log(`Wrote ${path.relative(ROOT, out)}`);
for (const [k, v] of Object.entries(counts)) console.log(`  ${k.padEnd(20)} ${v}`);
console.log('\nTo refresh the PDF: open /resume.html, Ctrl+P, Save as PDF → public/resume.pdf');
